services:
    admin.blog:
        class: BlogBundle\Admin\BlogAdmin
        arguments: [~, BlogBundle\Entity\Blog, ~]
        tags:
           - { name: sonata.admin, manager_type: orm, group: Main, label: Blog }
 #       public: true
