CvBundle\Entity\Image:
    type: entity
    repositoryClass: CvBundle\Entity\Repositories\ImageRepository
    table: image
    id:
        id:
            type:         integer
            generator:    { strategy: AUTO }
    fields:
        file:
            type:         string
            length:       255

        # changed when files are uploaded, to force preUpdate and postUpdate to fire
        updated:
            type:         datetime
            nullable:     true

        # ... other fields ...
    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]